name: Go + React Url shortener Full stack Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5


      - name: Debug secret (temporary - remove after)
        run: echo "DATABASE_URL length is ${#DATABASE_URL}"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install go-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate

      - name: Run migration on neon
        run: |
          migrate -path backend/internal/database/migrations -database "$DATABASE_URL" up
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

  deploy-frontend:          # <- this job is the frontend deployment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: |
          curl -X POST "${{ secrets.NETLIFY_BUILD_HOOK_URL }}"